# This workflow will build a Java project with Maven, and the DA-BPMN Docker image
# containing the node.js client part based on Theia Platform 

name: Build and create Docker Image

on:
  push:
    branches: [ "NourEldin-Ali:master" ]
  pull_request:
    branches: [ "NourEldin-Ali:master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Building DA-BPMN Server with Maven
      run: mvn -B package --file pom.xml

    - name: Building Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/NourEldin-Ali/da-bpmn:latest
          docker run ghcr.io/NourEldin-Ali/da-bpmn:latest
          docker push ghcr.io/NourEldin-Ali/da-bpmn:latest
    
